import { useQuery } from "@apollo/client";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GET_UNIVERSITIES } from "../utils/queries";

export default function Home() {
  const { loading, error, data } = useQuery(GET_UNIVERSITIES);

  if (loading) return <h1>Loading</h1>;
  if (error) return <>{error}</>;
  if (data) console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Unireview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
